#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = 
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -D_CONSOLE
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS)
OBJDIR_RELEASE = .objs
DEP_RELEASE = 
OUT_RELEASE = rtd2660

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -D_CONSOLE -D_CRT_SECURE_NO_WARNINGS
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = .objs
DEP_DEBUG = 
OUT_DEBUG = rtd2660

OBJ_RELEASE = $(OBJDIR_RELEASE)/RTD2662ModeTableDump.o $(OBJDIR_RELEASE)/crc.o $(OBJDIR_RELEASE)/gff.o $(OBJDIR_RELEASE)/i2c.o $(OBJDIR_RELEASE)/main.o

OBJ_DEBUG = $(OBJDIR_DEBUG)/RTD2662ModeTableDump.o $(OBJDIR_DEBUG)/crc.o $(OBJDIR_DEBUG)/gff.o $(OBJDIR_DEBUG)/i2c.o $(OBJDIR_DEBUG)/main.o

all: release debug

clean: clean_release clean_debug

before_release: 
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/RTD2662ModeTableDump.o: RTD2662ModeTableDump.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c RTD2662ModeTableDump.cpp -o $(OBJDIR_RELEASE)/RTD2662ModeTableDump.o

$(OBJDIR_RELEASE)/crc.o: crc.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c crc.cpp -o $(OBJDIR_RELEASE)/crc.o

$(OBJDIR_RELEASE)/gff.o: gff.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c gff.cpp -o $(OBJDIR_RELEASE)/gff.o

$(OBJDIR_RELEASE)/i2c.o: i2c.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c i2c.cpp -o $(OBJDIR_RELEASE)/i2c.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf $(OBJDIR_RELEASE)

before_debug: 
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/RTD2662ModeTableDump.o: RTD2662ModeTableDump.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c RTD2662ModeTableDump.cpp -o $(OBJDIR_DEBUG)/RTD2662ModeTableDump.o

$(OBJDIR_DEBUG)/crc.o: crc.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c crc.cpp -o $(OBJDIR_DEBUG)/crc.o

$(OBJDIR_DEBUG)/gff.o: gff.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c gff.cpp -o $(OBJDIR_DEBUG)/gff.o

$(OBJDIR_DEBUG)/i2c.o: i2c.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c i2c.cpp -o $(OBJDIR_DEBUG)/i2c.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf $(OBJDIR_DEBUG)

.PHONY: before_release after_release clean_release before_debug after_debug clean_debug

